// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYYj-wCxjHUxcQC-pPEPjkVdbvciw4jCY',
    appId: '1:681578119721:web:b267a0e8ed3b2e54049238',
    messagingSenderId: '681578119721',
    projectId: 'brew-crew-71684',
    authDomain: 'brew-crew-71684.firebaseapp.com',
    storageBucket: 'brew-crew-71684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCal3EahzAOePRfBLLHlBT0fa5v_qW6AyY',
    appId: '1:681578119721:android:6db414f6f6dcb3ee049238',
    messagingSenderId: '681578119721',
    projectId: 'brew-crew-71684',
    storageBucket: 'brew-crew-71684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIzECIHzEC2EVnxXmLeyjv0yw2uHPuWpc',
    appId: '1:681578119721:ios:b109fc2ffa49870e049238',
    messagingSenderId: '681578119721',
    projectId: 'brew-crew-71684',
    storageBucket: 'brew-crew-71684.appspot.com',
    iosClientId: '681578119721-7rtk4ratpitao74us9r5roukq3ered2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIzECIHzEC2EVnxXmLeyjv0yw2uHPuWpc',
    appId: '1:681578119721:ios:e6c20c11f434ec06049238',
    messagingSenderId: '681578119721',
    projectId: 'brew-crew-71684',
    storageBucket: 'brew-crew-71684.appspot.com',
    iosClientId: '681578119721-19kklmg75fdaj1f269n1e3k8bfc3r1o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
